    create table user_api_db (
        user_id bigint generated by default as identity,
        email varchar(255),
        name varchar(255),
        primary key (user_id)
    )


--    select * from user_api_db;
--
--    CREATE TABLE IF NOT EXIST user_api_db (
--        id SERIAL PRIMARY KEY,
--        name VARCHAR(100) NOT NULL,
--        email VARCHAR(100) NOT NULL UNIQUE
--    );
--
--    INSERT INTO user_api_db (name, email) VALUES ('John Doe', 'john.doe@gmail.com');
--    INSERT INTO user_api_db (name, email) VALUES ('Jane Smith', 'jane.smith@gmail.com');
--    INSERT INTO user_api_db (name, email) VALUES ('Alice Brown', 'alice.brown@gmail.com');

